name: 'dbt_attribution'
version: '1.0.0'
config-version: 2

profile: 'dbt_attribution'

model-paths: ['models']
test-paths: ['tests']
macro-paths: ['macros']

models:
  dbt_attribution:
    staging:
      +materialized: incremental
      +on_schema_change: append_new_columns
    intermediate:
      +materialized: incremental
      +on_schema_change: append_new_columns
    marts:
      +materialized: incremental
      +on_schema_change: append_new_columns

vars:
  ga4_project: 'bigquery-public-data'
  ga4_dataset: 'ga4_obfuscated_sample_ecommerce'
  attribution_window_days: 14
  session_timeout_minutes: 30